### ISSUE TITLE
Contribute words 

### ISSUE THREAD

**Issue by jackdonofrio** [Jack1q/haikugen#1]
You can contribute by adding words to [words.json](https://github.com/Jack1q/haikugen/blob/master/words.json).
Please make sure they are under the correct syllable category.
Words must fit within a 1 to 7 syllable category
Please run the contents of your modified version of words.json through https://jsonlint.com/ so I don't have to keep fixing your typos.

**Comment by edorguez** [comment]
Hi, I've added 7 words to 7 syllable words!

**Comment by Divyessh** [comment]
#13

**Comment by melissahuertadev** [comment]
I created PR #26 for this :)
